# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release tag (e.g. 1.5.0)'
        required: true
      source:
        description: 'Source of event'
        required: false
        default: 'No source specified'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.name }}
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.name }}
